/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminReportManagement: typeof import('./src/components/Admin/AdminReportManagement.vue')['default']
    AdminSensitiveWords: typeof import('./src/components/Admin/AdminSensitiveWords.vue')['default']
    AdminTeamReview: typeof import('./src/components/Admin/AdminTeamReview.vue')['default']
    AppFooter: typeof import('./src/components/Global/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/Global/AppHeader.vue')['default']
    AttributeIcon: typeof import('./src/components/TeamBuilder/AttributeIcon.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    EmailVerificationView: typeof import('./src/components/Auth/EmailVerificationView.vue')['default']
    LoginForm: typeof import('./src/components/Auth/LoginForm.vue')['default']
    PokemonStatPanel: typeof import('./src/components/TeamBuilder/PokemonStatPanel.vue')['default']
    RegisterForm: typeof import('./src/components/Auth/RegisterForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectionPanel: typeof import('./src/components/TeamBuilder/SelectionPanel.vue')['default']
    TeamBuilderMain: typeof import('./src/components/TeamBuilder/TeamBuilderMain.vue')['default']
    TeamCard: typeof import('./src/components/Team/TeamCard.vue')['default']
    TeamPokemonConfig: typeof import('./src/components/TeamBuilder/TeamPokemonConfig.vue')['default']
    UserFavoriteList: typeof import('./src/components/User/UserFavoriteList.vue')['default']
    UserProfile: typeof import('./src/components/User/UserProfile.vue')['default']
    UserTeamList: typeof import('./src/components/User/UserTeamList.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
