"""Add tera_type to TeamPokemon

Revision ID: 6ee064ee5193
Revises: a45382e0c8c9
Create Date: 2025-06-02 15:50:51.361674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ee064ee5193'
down_revision = 'a45382e0c8c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tera_type', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_pokemon', schema=None) as batch_op:
        batch_op.drop_column('tera_type')

    # ### end Alembic commands ###
