"""add pokemon_move_learnset table

Revision ID: 7c2392d4889c
Revises: 20250525
Create Date: 2025-05-26 17:54:03.110129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c2392d4889c'
down_revision = '20250525'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon_move_learnset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pokemon_species_id', sa.Integer(), nullable=False),
    sa.Column('move_id', sa.Integer(), nullable=False),
    sa.Column('version_group_id', sa.Integer(), nullable=False),
    sa.Column('learn_method', sa.String(length=50), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['move_id'], ['moves.id'], ),
    sa.ForeignKeyConstraint(['pokemon_species_id'], ['pokemon_species.id'], ),
    sa.ForeignKeyConstraint(['version_group_id'], ['version_groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pokemon_species_id', 'move_id', 'version_group_id', 'learn_method', 'level', name='uq_pokemon_move_learnset')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pokemon_move_learnset')
    # ### end Alembic commands ###
