"""add pokemon form/generation relation

Revision ID: 8a9e5001f68c
Revises: bd8e332ea645
Create Date: 2025-05-25 11:06:05.585362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a9e5001f68c'
down_revision = 'bd8e332ea645'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generation_pokemon_species',
    sa.Column('generation_id', sa.Integer(), nullable=False),
    sa.Column('pokemon_species_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['generation_id'], ['generations.id'], ),
    sa.ForeignKeyConstraint(['pokemon_species_id'], ['pokemon_species.id'], ),
    sa.PrimaryKeyConstraint('generation_id', 'pokemon_species_id')
    )
    op.create_table('pokemon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('form_name', sa.String(length=100), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('sprite', sa.String(length=255), nullable=True),
    sa.Column('type_1', sa.String(length=50), nullable=True),
    sa.Column('type_2', sa.String(length=50), nullable=True),
    sa.Column('base_hp', sa.Integer(), nullable=True),
    sa.Column('base_atk', sa.Integer(), nullable=True),
    sa.Column('base_def', sa.Integer(), nullable=True),
    sa.Column('base_spa', sa.Integer(), nullable=True),
    sa.Column('base_spd', sa.Integer(), nullable=True),
    sa.Column('base_spe', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['species_id'], ['pokemon_species.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pokemon_species', schema=None) as batch_op:
        batch_op.drop_column('generation')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon_species', schema=None) as batch_op:
        batch_op.add_column(sa.Column('generation', sa.VARCHAR(length=20), nullable=True))

    op.drop_table('pokemon')
    op.drop_table('generation_pokemon_species')
    # ### end Alembic commands ###
