"""add zh fields for pokemon and move

Revision ID: 9381458f1928
Revises: 
Create Date: 2025-05-23 11:22:52.906189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9381458f1928'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon_moves', schema=None) as batch_op:
        batch_op.add_column(sa.Column('move_name_zh', sa.String(length=100), nullable=True))
        batch_op.drop_column('pp')

    with op.batch_alter_table('team_pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('species_name_zh', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_pokemon', schema=None) as batch_op:
        batch_op.drop_column('species_name_zh')

    with op.batch_alter_table('pokemon_moves', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pp', sa.INTEGER(), nullable=True))
        batch_op.drop_column('move_name_zh')

    # ### end Alembic commands ###
