"""updated likes, favorites and external link -repair

Revision ID: 9d73f954575e
Revises: da05edd3a99d
Create Date: 2025-06-03 18:13:51.213041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d73f954575e'
down_revision = 'da05edd3a99d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon_moves', schema=None) as batch_op:
        batch_op.create_unique_constraint('_pokemon_move_uc', ['pokemon_id', 'move_id'])

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorites_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('likes_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_column('likes_count')
        batch_op.drop_column('favorites_count')

    with op.batch_alter_table('pokemon_moves', schema=None) as batch_op:
        batch_op.drop_constraint('_pokemon_move_uc', type_='unique')

    # ### end Alembic commands ###
