"""add indexes to models

Revision ID: a45382e0c8c9
Revises: 20250527_update_generation_pokemon_species_unique
Create Date: 2025-05-28 20:26:28.282170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a45382e0c8c9'
down_revision = '20250527_update_generation_pokemon_species_unique'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('abilities', schema=None) as batch_op:
        batch_op.create_index('ix_ability_name_zh_hans', ['name_zh_hans'], unique=False)

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_index('ix_item_category', ['category'], unique=False)
        batch_op.create_index('ix_item_generation', ['generation'], unique=False)
        batch_op.create_index('ix_item_name_zh_hans', ['name_zh_hans'], unique=False)

    with op.batch_alter_table('moves', schema=None) as batch_op:
        batch_op.create_index('ix_move_category', ['category'], unique=False)
        batch_op.create_index('ix_move_generation', ['generation'], unique=False)
        batch_op.create_index('ix_move_name_zh_hans', ['name_zh_hans'], unique=False)
        batch_op.create_index('ix_move_type', ['type'], unique=False)

    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.create_index('ix_pokemon_first_generation_id', ['first_generation_id'], unique=False)
        batch_op.create_index('ix_pokemon_name', ['name'], unique=False)
        batch_op.create_index('ix_pokemon_species_id', ['species_id'], unique=False)

    with op.batch_alter_table('pokemon_move_learnset', schema=None) as batch_op:
        batch_op.create_index('ix_learnset_move_id', ['move_id'], unique=False)
        batch_op.create_index('ix_learnset_pokemon_species_version_group', ['pokemon_species_id', 'version_group_id'], unique=False)

    with op.batch_alter_table('pokemon_species', schema=None) as batch_op:
        batch_op.create_index('ix_pokemonspecies_id', ['id'], unique=False)
        batch_op.create_index('ix_pokemonspecies_name', ['name'], unique=False)
        batch_op.create_index('ix_pokemonspecies_name_zh_hans', ['name_zh_hans'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon_species', schema=None) as batch_op:
        batch_op.drop_index('ix_pokemonspecies_name_zh_hans')
        batch_op.drop_index('ix_pokemonspecies_name')
        batch_op.drop_index('ix_pokemonspecies_id')

    with op.batch_alter_table('pokemon_move_learnset', schema=None) as batch_op:
        batch_op.drop_index('ix_learnset_pokemon_species_version_group')
        batch_op.drop_index('ix_learnset_move_id')

    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.drop_index('ix_pokemon_species_id')
        batch_op.drop_index('ix_pokemon_name')
        batch_op.drop_index('ix_pokemon_first_generation_id')

    with op.batch_alter_table('moves', schema=None) as batch_op:
        batch_op.drop_index('ix_move_type')
        batch_op.drop_index('ix_move_name_zh_hans')
        batch_op.drop_index('ix_move_generation')
        batch_op.drop_index('ix_move_category')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index('ix_item_name_zh_hans')
        batch_op.drop_index('ix_item_generation')
        batch_op.drop_index('ix_item_category')

    with op.batch_alter_table('abilities', schema=None) as batch_op:
        batch_op.drop_index('ix_ability_name_zh_hans')

    # ### end Alembic commands ###
