"""Add Token to teams

Revision ID: bc5acc45c71a
Revises: 6ee064ee5193
Create Date: 2025-06-03 11:45:56.744149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc5acc45c71a'
down_revision = '6ee064ee5193'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_teams_token'), ['token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_token'))
        batch_op.drop_column('token')

    # ### end Alembic commands ###
